name = "math-act-worker"
main = "src/index.js"
compatibility_date = "2024-09-01"

[[d1_databases]]
binding = "DB"                # must match env.DB in index.js
database_name = "math-act-db"
database_id = "44620928-3c8b-4be7-8bc6-2834a9810576"    # Wrangler will create this
